"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BarChart3, Check, Copy, Download, ExternalLink, Eye, FileText, Globe2, Link2, MessageSquareText, MoreHorizontal, QrCode, Save, Send, Settings2 } from "lucide-react";
import { Shell } from "@/components/shell";
import { LunaFormEditor } from "@/components/luna-form-editor";
import { Badge, Loading } from "@/components/ui";
import { API_URL, api } from "@/lib/api";
import type { Campaign } from "@/lib/types";

export default function CampaignDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [campaign, setCampaign] = useState<Campaign | null>(null); const [tab, setTab] = useState("overview"); const [saved, setSaved] = useState(false);
  const load = () => api<Campaign>(`/campaigns/${id}`).then(setCampaign);
  useEffect(() => { void load(); if (new URLSearchParams(window.location.search).get("tab") === "form") setTab("form"); }, [id]);
  async function publish() { if (!campaign) return; const updated = await api<Campaign>(`/campaigns/${id}`, { method: "PATCH", body: JSON.stringify({ status: campaign.status === "active" ? "draft" : "active" }) }); setCampaign(updated); }
  async function saveThankYou(data: Record<string, string>) { const updated = await api<Campaign>(`/campaigns/${id}`, { method: "PATCH", body: JSON.stringify({ thank_you: data }) }); setCampaign(updated); setSaved(true); setTimeout(() => setSaved(false), 1800); }
  if (!campaign) return <Shell><Loading/></Shell>;
  return <Shell><div className="detail-page"><div className="detail-top"><Link href="/campaigns" className="back-link"><ArrowLeft size={18}/>Campagnes</Link><div className="detail-actions"><a href={`/forms/${campaign.slug}`} target="_blank" className="button button-secondary"><Eye size={18}/>Prévisualiser</a><button onClick={publish} className="button button-primary">{campaign.status === "active" ? "Mettre en pause" : <><Send size={17}/>Publier</>}</button></div></div><header className="campaign-title"><div><div className="title-line"><h1>{campaign.name}</h1><Badge tone={campaign.status === "active" ? "green" : "amber"}>{campaign.status === "active" ? "Active" : "Brouillon"}</Badge></div><p>{campaign.description}</p></div><button className="icon-button"><MoreHorizontal/></button></header><nav className="detail-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}><BarChart3 size={18}/>Vue d’ensemble</button><button className={tab === "form" ? "active" : ""} onClick={() => setTab("form")}><FileText size={18}/>Formulaire</button><button className={tab === "responses" ? "active" : ""} onClick={() => setTab("responses")}><MessageSquareText size={18}/>Réponses <span>{campaign.responses}</span></button><button className={tab === "share" ? "active" : ""} onClick={() => setTab("share")}><Globe2 size={18}/>Diffusion</button><button className={tab === "tunnel" ? "active" : ""} onClick={() => setTab("tunnel")}><Settings2 size={18}/>Tunnel</button></nav>
    {tab === "overview" && <Overview campaign={campaign} onEdit={() => setTab("form")}/>} {tab === "form" && <LunaFormEditor campaign={campaign} onCampaignChange={setCampaign}/>} {tab === "responses" && <Responses campaign={campaign}/>} {tab === "share" && <Share campaign={campaign}/>} {tab === "tunnel" && <Tunnel campaign={campaign} onSave={saveThankYou} saved={saved}/>}</div></Shell>;
}

function Overview({ campaign, onEdit }: { campaign: Campaign; onEdit: () => void }) { return <div className="detail-content"><section className="metric-grid metric-grid-3"><article className="metric-card"><p>Visites</p><strong>{campaign.visits}</strong><span>Depuis la création</span></article><article className="metric-card"><p>Réponses</p><strong>{campaign.responses}</strong><span className="positive">↗ Collectées</span></article><article className="metric-card"><p>Conversion</p><strong>{campaign.conversion} %</strong><span>Visite → réponse</span></article></section><div className="detail-grid"><article className="panel"><div className="panel-head"><div><p className="eyebrow">FORMULAIRE</p><h2>{campaign.fields.length} champs configurés</h2></div><button className="text-link" onClick={onEdit}>Modifier avec Luna</button></div><div className="field-summary">{campaign.fields.map((f, i) => <div key={f.id}><span>{String(i + 1).padStart(2, "0")}</span><strong>{f.label}</strong><small>{labelType(f.type)}{f.required ? " · requis" : ""}</small></div>)}</div></article><article className="panel health-card"><p className="eyebrow">QUALITÉ</p><h2>Prête à convertir</h2><div className="health-score"><strong>92</strong><span>/100</span></div><ul><li><Check/>Formulaire court</li><li><Check/>Consentement conforme</li><li><Check/>Mobile optimisé</li></ul></article></div></div>; }

function Responses({ campaign }: { campaign: Campaign }) { const [rows, setRows] = useState<{id:string; answers:Record<string, string|number>;source:string;consent:boolean;created_at:string}[] | null>(null); useEffect(() => { api<typeof rows>(`/campaigns/${campaign.id}/responses`).then(setRows); }, [campaign.id]); const token = typeof window !== "undefined" ? localStorage.getItem("sillage_token") : ""; return <div className="detail-content"><div className="response-tools"><div><p className="eyebrow">DONNÉES</p><h2>{campaign.responses} réponses</h2></div><a className="button button-secondary" href={`${API_URL}/campaigns/${campaign.id}/export.csv`} onClick={e => { e.preventDefault(); fetch(`${API_URL}/campaigns/${campaign.id}/export.csv`, { headers: { Authorization: `Bearer ${token}` }}).then(r=>r.blob()).then(b=>{const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=`${campaign.slug}.csv`;a.click();URL.revokeObjectURL(u);}); }}><Download size={17}/>Exporter CSV</a></div>{rows === null ? <Loading/> : <div className="responses-table panel"><div className="response-table-head"><span>Contact</span><span>Source</span><span>Consentement</span><span>Reçue le</span></div>{rows.map(r => <div className="response-table-row" key={r.id}><div><strong>{r.answers.name || "Réponse anonyme"}</strong><span>{r.answers.email || r.answers.comment || "—"}</span></div><Badge>{r.source}</Badge><span className="consent-ok"><Check size={15}/>{r.consent ? "Recueilli" : "Non"}</span><span>{new Intl.DateTimeFormat("fr-FR", {dateStyle:"medium"}).format(new Date(r.created_at))}</span></div>)}</div>}</div>; }

function Share({ campaign }: { campaign: Campaign }) { const url = typeof window !== "undefined" ? `${window.location.origin}/forms/${campaign.slug}` : `/forms/${campaign.slug}`; const [copied, setCopied] = useState(false); const copy = () => navigator.clipboard.writeText(url).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1500); }); return <div className="detail-content"><div className="share-hero"><p className="eyebrow">DIFFUSION</p><h2>Partagez votre campagne partout.</h2><p>Chaque canal est identifié automatiquement dans vos statistiques.</p><div className="copy-field"><Link2 size={18}/><span>{url}</span><button onClick={copy}>{copied ? <><Check size={17}/>Copié</> : <><Copy size={17}/>Copier</>}</button></div></div><div className="share-grid"><ShareCard icon={<QrCode/>} title="QR Code" text="Pour vos affiches, comptoirs et événements."/><ShareCard icon={<ExternalLink/>} title="Intégration web" text="Iframe responsive pour votre site."/><ShareCard icon={<Send/>} title="Email & SMS" text="Un lien court prêt à envoyer."/></div></div>; }
function ShareCard({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <article className="panel share-card"><div className="metric-icon">{icon}</div><h3>{title}</h3><p>{text}</p><button className="text-link">Configurer <ExternalLink size={15}/></button></article>; }

function Tunnel({ campaign, onSave, saved }: { campaign: Campaign; onSave: (data:Record<string,string>)=>void; saved:boolean }) { const [data,setData]=useState<Record<string,string>>(campaign.thank_you); return <div className="detail-content"><div className="tunnel-grid"><div className="panel tunnel-config"><p className="eyebrow">APRÈS L’ENVOI</p><h2>Page de remerciement</h2><label>Titre<input value={data.title || ""} onChange={e=>setData({...data,title:e.target.value})}/></label><label>Message<textarea value={data.message || ""} onChange={e=>setData({...data,message:e.target.value})}/></label><label>Action<select value={data.action || "none"} onChange={e=>setData({...data,action:e.target.value})}><option value="none">Aucune action</option><option value="cta">Bouton vers une page</option><option value="redirect">Redirection automatique</option><option value="promo">Afficher un code promo</option></select></label>{data.action !== "none" && <><label>Texte du bouton<input value={data.button_label || ""} onChange={e=>setData({...data,button_label:e.target.value})}/></label><label>URL de destination<input value={data.button_url || ""} onChange={e=>setData({...data,button_url:e.target.value})}/></label></>}<button className="button button-primary" onClick={()=>onSave(data)}>{saved ? <><Check size={17}/>Enregistré</> : <><Save size={17}/>Enregistrer</>}</button></div><div className="thanks-preview"><div className="client-monogram">AR</div><div className="thanks-check"><Check/></div><h2>{data.title?.replace("{prenom}", "Léa")}</h2><p>{data.message}</p>{data.action !== "none" && <button className="button button-primary">{data.button_label || "Continuer"}</button>}<small>Atelier Rivage · Mentions légales</small></div></div></div>; }

function labelType(type:string){return ({text:"Texte court",email:"Email",tel:"Téléphone",textarea:"Texte long",radio:"Choix unique",select:"Liste",rating:"Note",consent:"Consentement",date:"Date",file:"Fichier",number:"Nombre"} as Record<string,string>)[type] || type;}
